[project]
name = "sensitivities"
version = "1.0.0"
requires-python = ">=3.10"

dependencies = [
    "numpy",
    "scipy",
]

[project.optional-dependencies]
dev = [
    "build",
    "pytest",
    "black",
    "matplotlib"
]